/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.cristiangarcia.principal;
import java.awt.Color;
import org.cristiangarcia.crud.FuncionesVuelos;
import org.cristiangarcia.crudcliente.FuncionesCliente;
import org.cristiangarcia.hoteles.FuncionesHotel;
import org.cristiangarcia.login.Login;
/**
 *
 * @author crist
 */
public class VentanaInicio extends javax.swing.JFrame {

    /**
     * Creates new form VentanaInicio
     */
    public VentanaInicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnRegresarLogin = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        btnVerClientes = new javax.swing.JButton();
        btnHoteles = new javax.swing.JButton();
        btnVerVuelosPrn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lemon Days", 0, 36)); // NOI18N
        jLabel1.setText("AGENCIA DE VIAJES");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 31, -1, -1));

        jPanel1.setBackground(new java.awt.Color(211, 206, 223));
        jPanel1.setMaximumSize(new java.awt.Dimension(502, 326));
        jPanel1.setMinimumSize(new java.awt.Dimension(502, 326));
        jPanel1.setPreferredSize(new java.awt.Dimension(502, 326));

        btnRegresarLogin.setBackground(new java.awt.Color(201, 187, 207));
        btnRegresarLogin.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        btnRegresarLogin.setText("REGRESAR");
        btnRegresarLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegresarLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRegresarLoginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRegresarLoginMouseExited(evt);
            }
        });
        btnRegresarLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarLoginActionPerformed(evt);
            }
        });

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));

        btnVerClientes.setBackground(new java.awt.Color(201, 187, 207));
        btnVerClientes.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        btnVerClientes.setText("Ver Clientes ");
        btnVerClientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVerClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnVerClientesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnVerClientesMouseExited(evt);
            }
        });
        btnVerClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerClientesActionPerformed(evt);
            }
        });

        btnHoteles.setBackground(new java.awt.Color(201, 187, 207));
        btnHoteles.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        btnHoteles.setText("Ver Hoteles");
        btnHoteles.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHoteles.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnHotelesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnHotelesMouseExited(evt);
            }
        });
        btnHoteles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHotelesActionPerformed(evt);
            }
        });

        btnVerVuelosPrn.setBackground(new java.awt.Color(201, 187, 207));
        btnVerVuelosPrn.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        btnVerVuelosPrn.setText("Ver Vuelos");
        btnVerVuelosPrn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVerVuelosPrn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnVerVuelosPrnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnVerVuelosPrnMouseExited(evt);
            }
        });
        btnVerVuelosPrn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerVuelosPrnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator1)
                            .addComponent(jSeparator2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnVerClientes)
                                .addGap(78, 78, 78)
                                .addComponent(btnHoteles, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                                .addComponent(btnVerVuelosPrn))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(193, 193, 193)
                        .addComponent(btnRegresarLogin)))
                .addContainerGap(8, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnHoteles, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(btnVerClientes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnVerVuelosPrn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                .addComponent(btnRegresarLogin)
                .addGap(31, 31, 31))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 502, 326));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVerVuelosPrnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerVuelosPrnActionPerformed
        // TODO add your handling code here:
        FuncionesVuelos ps = new FuncionesVuelos();
        ps.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_btnVerVuelosPrnActionPerformed

    private void btnVerClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerClientesActionPerformed
        // TODO add your handling code here:
        FuncionesCliente ko = new FuncionesCliente();
        ko.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnVerClientesActionPerformed

    private void btnHotelesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHotelesActionPerformed
        // TODO add your handling code here:
        FuncionesHotel lo = new FuncionesHotel();
        lo.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnHotelesActionPerformed

    private void btnRegresarLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarLoginActionPerformed
        // TODO add your handling code here:
        Login ngt = new Login ();
        ngt.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnRegresarLoginActionPerformed

    private void btnVerClientesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVerClientesMouseEntered
        // TODO add your handling code here:
        btnVerClientes.setBackground(Color.black);
        btnVerClientes.setForeground(new Color(201, 187, 207));
    }//GEN-LAST:event_btnVerClientesMouseEntered

    private void btnVerClientesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVerClientesMouseExited
        // TODO add your handling code here:
        btnVerClientes.setBackground(new Color(201, 187, 207));
        btnVerClientes.setForeground(Color.black);
    }//GEN-LAST:event_btnVerClientesMouseExited

    private void btnHotelesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHotelesMouseEntered
        // TODO add your handling code here:
        btnHoteles.setBackground(Color.black);
        btnHoteles.setForeground(new Color(201, 187, 207));
    }//GEN-LAST:event_btnHotelesMouseEntered

    private void btnHotelesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHotelesMouseExited
        // TODO add your handling code here:
        btnHoteles.setBackground(new Color(201, 187, 207));
        btnHoteles.setForeground(Color.black);
    }//GEN-LAST:event_btnHotelesMouseExited

    private void btnVerVuelosPrnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVerVuelosPrnMouseEntered
        // TODO add your handling code here:
        btnVerVuelosPrn.setBackground(Color.black);
        btnVerVuelosPrn.setForeground(new Color(201, 187, 207));
    }//GEN-LAST:event_btnVerVuelosPrnMouseEntered

    private void btnVerVuelosPrnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVerVuelosPrnMouseExited
        // TODO add your handling code here:
        btnVerVuelosPrn.setBackground(new Color(201, 187, 207));
        btnVerVuelosPrn.setForeground(Color.black);
    }//GEN-LAST:event_btnVerVuelosPrnMouseExited

    private void btnRegresarLoginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegresarLoginMouseEntered
        // TODO add your handling code here:
        btnRegresarLogin.setBackground(Color.cyan);
        btnRegresarLogin.setForeground(Color.black);
    }//GEN-LAST:event_btnRegresarLoginMouseEntered

    private void btnRegresarLoginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegresarLoginMouseExited
        // TODO add your handling code here:
        btnRegresarLogin.setBackground(new Color(201, 187, 207));
        btnRegresarLogin.setForeground(Color.black);
    }//GEN-LAST:event_btnRegresarLoginMouseExited

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHoteles;
    private javax.swing.JButton btnRegresarLogin;
    private javax.swing.JButton btnVerClientes;
    private javax.swing.JButton btnVerVuelosPrn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables

    public void setVisble(boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
