/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.cristiangarcia.crud;
import java.awt.Color;
import java.util.HashSet;
import java.util.Set;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.cristiangarcia.principal.VentanaInicio;

/**
 *
 * @author crist
 */
public class FuncionesVuelos extends javax.swing.JFrame {
    DefaultTableModel modelo;
    /**
     * Creates new form crudVuelos
     */
    public FuncionesVuelos() {
        initComponents();
        modelo = new DefaultTableModel();
        modelo.addColumn("Id");
        modelo.addColumn("Aerolinea");
        modelo.addColumn("Arpto.de Salida");
        modelo.addColumn("Arpto.de Llegada");
        modelo.addColumn("Precio");
        this.tabla.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblId = new javax.swing.JLabel();
        lblAerolinea = new javax.swing.JLabel();
        lblArptoDeSalida = new javax.swing.JLabel();
        lblArptoDeLlegada = new javax.swing.JLabel();
        lblPrecio = new javax.swing.JLabel();
        txtIdVuelo = new javax.swing.JTextField();
        txtAerolinea = new javax.swing.JTextField();
        txtArptoDeSalida = new javax.swing.JTextField();
        txtArptoDeLlegada = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();
        btnAgregarVuelo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        btnEliminar = new javax.swing.JButton();
        lblFilaVuelo = new javax.swing.JLabel();
        lblColumnaVuelo = new javax.swing.JLabel();
        lblNuevoDatoVuelo = new javax.swing.JLabel();
        txtFilaVuelo = new javax.swing.JTextField();
        txtColumnaVuelo = new javax.swing.JTextField();
        txtNuevoDatoVuelo = new javax.swing.JTextField();
        btnEliminarTdoVuelo = new javax.swing.JButton();
        btnModificarVuelo = new javax.swing.JButton();
        btnRegresarVuelo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblId.setText("ID");

        lblAerolinea.setText("Aerolinea");

        lblArptoDeSalida.setText("Arpto. de Salida");

        lblArptoDeLlegada.setText("Arpto. de Llegada");

        lblPrecio.setText("Precio");

        txtIdVuelo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        txtAerolinea.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        txtArptoDeSalida.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        txtArptoDeLlegada.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        txtPrecio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnAgregarVuelo.setText("AGREGAR DATOS");
        btnAgregarVuelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarVueloActionPerformed(evt);
            }
        });

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Aerolinea", "Arpto. de Salida", "Arpto. de Llegada", "Precio"
            }
        ));
        jScrollPane1.setViewportView(tabla);

        btnEliminar.setText("ELIMINAR DATOS");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        lblFilaVuelo.setText("Fila");

        lblColumnaVuelo.setText("Columna");

        lblNuevoDatoVuelo.setText("Nuevo Dato");

        txtFilaVuelo.setBackground(new java.awt.Color(0, 0, 0));
        txtFilaVuelo.setForeground(new java.awt.Color(255, 255, 255));
        txtFilaVuelo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        txtColumnaVuelo.setBackground(new java.awt.Color(0, 0, 0));
        txtColumnaVuelo.setForeground(new java.awt.Color(255, 255, 255));
        txtColumnaVuelo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        txtNuevoDatoVuelo.setBackground(new java.awt.Color(204, 255, 204));
        txtNuevoDatoVuelo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnEliminarTdoVuelo.setText("ELIMINAR TODO");
        btnEliminarTdoVuelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarTdoVueloActionPerformed(evt);
            }
        });

        btnModificarVuelo.setText("MODIFICAR DATOS");
        btnModificarVuelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarVueloActionPerformed(evt);
            }
        });

        btnRegresarVuelo.setBackground(new java.awt.Color(0, 0, 0));
        btnRegresarVuelo.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        btnRegresarVuelo.setForeground(new java.awt.Color(255, 255, 255));
        btnRegresarVuelo.setText("REGRESAR");
        btnRegresarVuelo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegresarVuelo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRegresarVueloMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRegresarVueloMouseExited(evt);
            }
        });
        btnRegresarVuelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarVueloActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblId)
                            .addComponent(lblAerolinea)
                            .addComponent(lblArptoDeSalida)
                            .addComponent(lblArptoDeLlegada)
                            .addComponent(lblPrecio))
                        .addGap(89, 89, 89)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtArptoDeSalida, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAerolinea, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtArptoDeLlegada, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                            .addComponent(txtIdVuelo, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPrecio)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnModificarVuelo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEliminarTdoVuelo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAgregarVuelo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btnRegresarVuelo))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFilaVuelo)
                            .addComponent(lblColumnaVuelo)
                            .addComponent(lblNuevoDatoVuelo))
                        .addGap(109, 109, 109)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNuevoDatoVuelo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtColumnaVuelo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFilaVuelo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 489, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblFilaVuelo)
                            .addComponent(txtFilaVuelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblColumnaVuelo)
                            .addComponent(txtColumnaVuelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNuevoDatoVuelo)
                            .addComponent(txtNuevoDatoVuelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblId)
                            .addComponent(txtIdVuelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblAerolinea)
                            .addComponent(txtAerolinea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblArptoDeSalida)
                            .addComponent(txtArptoDeSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblArptoDeLlegada)
                            .addComponent(txtArptoDeLlegada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPrecio)
                            .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addComponent(btnAgregarVuelo)
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminarTdoVuelo)
                        .addGap(18, 18, 18)
                        .addComponent(btnModificarVuelo)
                        .addGap(18, 18, 18)
                        .addComponent(btnRegresarVuelo)))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarVueloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarVueloActionPerformed
            // TODO add your handling code here:
            String []datos = new String[5];
            datos [0] = txtIdVuelo.getText();
            datos [1] = txtAerolinea.getText();
            datos [2] = txtArptoDeSalida.getText();
            datos [3] = txtArptoDeLlegada.getText();
            datos [4] = txtPrecio.getText();
            modelo.addRow(datos);
            txtIdVuelo.setText("");
            txtAerolinea.setText("");
            txtArptoDeSalida.setText("");
            txtArptoDeLlegada.setText("");
            txtPrecio.setText("");
        
    }//GEN-LAST:event_btnAgregarVueloActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        int fila = tabla.getSelectedRow();
        if (fila >=0){
            modelo.removeRow(fila);
        }else{
            JOptionPane.showMessageDialog(null, "Seleccionar Fila");
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnEliminarTdoVueloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarTdoVueloActionPerformed
        // TODO add your handling code here:
        int fila = tabla.getRowCount();
        for (int i = fila -1;i>=0;i--){
            modelo.removeRow(i);
        }
    }//GEN-LAST:event_btnEliminarTdoVueloActionPerformed

    private void btnModificarVueloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarVueloActionPerformed
        // TODO add your handling code here:
        int fila = Integer.parseInt(txtFilaVuelo.getText());
        int columna = Integer.parseInt(txtColumnaVuelo.getText());
        modelo.setValueAt(txtNuevoDatoVuelo.getText(), fila, columna);
        //PARA QUE FUNCIONE, SE CUENTA DESDE 0 
        //COLUMNA ID = 0, AEROLINEA = 1, Y ASI SUCESIVAMENTE 
    }//GEN-LAST:event_btnModificarVueloActionPerformed

    private void btnRegresarVueloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarVueloActionPerformed
        // TODO add your handling code here:
        VentanaInicio dx = new VentanaInicio();
        dx.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_btnRegresarVueloActionPerformed

    private void btnRegresarVueloMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegresarVueloMouseEntered
        // TODO add your handling code here:
        btnRegresarVuelo.setBackground(Color.cyan);
        btnRegresarVuelo.setForeground(Color.black);
    }//GEN-LAST:event_btnRegresarVueloMouseEntered

    private void btnRegresarVueloMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegresarVueloMouseExited
        // TODO add your handling code here:
        btnRegresarVuelo.setBackground(Color.black);
        btnRegresarVuelo.setForeground(Color.white);
    }//GEN-LAST:event_btnRegresarVueloMouseExited

   
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarVuelo;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnEliminarTdoVuelo;
    private javax.swing.JButton btnModificarVuelo;
    private javax.swing.JButton btnRegresarVuelo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAerolinea;
    private javax.swing.JLabel lblArptoDeLlegada;
    private javax.swing.JLabel lblArptoDeSalida;
    private javax.swing.JLabel lblColumnaVuelo;
    private javax.swing.JLabel lblFilaVuelo;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblNuevoDatoVuelo;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JTable tabla;
    private javax.swing.JTextField txtAerolinea;
    private javax.swing.JTextField txtArptoDeLlegada;
    private javax.swing.JTextField txtArptoDeSalida;
    private javax.swing.JTextField txtColumnaVuelo;
    private javax.swing.JTextField txtFilaVuelo;
    private javax.swing.JTextField txtIdVuelo;
    private javax.swing.JTextField txtNuevoDatoVuelo;
    private javax.swing.JTextField txtPrecio;
    // End of variables declaration//GEN-END:variables
}
