/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.cristiangarcia.crudcliente;
import java.awt.Color;
import java.util.HashSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.cristiangarcia.principal.VentanaInicio;
/**
 *
 * @author crist
 */
public class FuncionesCliente extends javax.swing.JFrame {
    DefaultTableModel modelo;
    /**
     * Creates new form FuncionesCliente
     */
    public FuncionesCliente() {
        initComponents();
        modelo = new DefaultTableModel();
        modelo.addColumn("ID");
        modelo.addColumn("Nombre");
        modelo.addColumn("Apellido");
        modelo.addColumn("Genero");
        modelo.addColumn("Edad");
        modelo.addColumn("Contacto");
        this.tablaCliente.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblIdCliente = new javax.swing.JLabel();
        lblNombreCliente = new javax.swing.JLabel();
        lblApellidoCliente = new javax.swing.JLabel();
        lblGeneroCliente = new javax.swing.JLabel();
        lblEdadCliente = new javax.swing.JLabel();
        lblContactoCliente = new javax.swing.JLabel();
        txtIdCliente = new javax.swing.JTextField();
        txtNombreCliente = new javax.swing.JTextField();
        txtApellidoCliente = new javax.swing.JTextField();
        txtGeneroCliente = new javax.swing.JTextField();
        txtEdadCliente = new javax.swing.JTextField();
        txtContactoCliente = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaCliente = new javax.swing.JTable();
        btnAgregarCliente = new javax.swing.JButton();
        btnEliminarCliente = new javax.swing.JButton();
        btnEliminarTdoCliente = new javax.swing.JButton();
        btnModificarCliente = new javax.swing.JButton();
        lblFilaCliente = new javax.swing.JLabel();
        lblColumnaCliente = new javax.swing.JLabel();
        lblNuevoDatoCliente = new javax.swing.JLabel();
        txtFilaCliente = new javax.swing.JTextField();
        txtColumnaCliente = new javax.swing.JTextField();
        txtNuevoDatoCliente = new javax.swing.JTextField();
        btnRegresarVentanaInicio = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximizedBounds(new java.awt.Rectangle(0, 0, 842, 550));
        setMaximumSize(new java.awt.Dimension(842, 550));
        setMinimumSize(new java.awt.Dimension(842, 550));
        setPreferredSize(new java.awt.Dimension(842, 550));
        setSize(new java.awt.Dimension(842, 550));

        lblIdCliente.setText("ID");

        lblNombreCliente.setText("Nombre");

        lblApellidoCliente.setText("Apellido");

        lblGeneroCliente.setText("Género");

        lblEdadCliente.setText("Edad");

        lblContactoCliente.setText("Contacto");

        txtIdCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        txtNombreCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        txtApellidoCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        txtGeneroCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        txtEdadCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        txtContactoCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        tablaCliente.setBackground(new java.awt.Color(204, 255, 255));
        tablaCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Apellido", "Genero", "Edad", "Contacto"
            }
        ));
        jScrollPane1.setViewportView(tablaCliente);

        btnAgregarCliente.setText("AGREGAR DATOS");
        btnAgregarCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgregarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarClienteActionPerformed(evt);
            }
        });

        btnEliminarCliente.setText("ELIMINAR DATOS");
        btnEliminarCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarClienteActionPerformed(evt);
            }
        });

        btnEliminarTdoCliente.setText("ELIMINAR TODO");
        btnEliminarTdoCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminarTdoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarTdoClienteActionPerformed(evt);
            }
        });

        btnModificarCliente.setText("MODIFICAR DATO");
        btnModificarCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnModificarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarClienteActionPerformed(evt);
            }
        });

        lblFilaCliente.setText("Fila");

        lblColumnaCliente.setText("Columna");

        lblNuevoDatoCliente.setText("Nuevo Dato");

        txtFilaCliente.setBackground(new java.awt.Color(0, 0, 0));
        txtFilaCliente.setForeground(new java.awt.Color(255, 255, 255));
        txtFilaCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtFilaCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtFilaClienteMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtFilaClienteMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtFilaClienteMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                txtFilaClienteMouseReleased(evt);
            }
        });

        txtColumnaCliente.setBackground(new java.awt.Color(0, 0, 0));
        txtColumnaCliente.setForeground(new java.awt.Color(255, 255, 255));
        txtColumnaCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        txtNuevoDatoCliente.setBackground(new java.awt.Color(204, 255, 204));
        txtNuevoDatoCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnRegresarVentanaInicio.setBackground(new java.awt.Color(0, 0, 0));
        btnRegresarVentanaInicio.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btnRegresarVentanaInicio.setForeground(new java.awt.Color(255, 255, 255));
        btnRegresarVentanaInicio.setText("REGRESAR");
        btnRegresarVentanaInicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegresarVentanaInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRegresarVentanaInicioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRegresarVentanaInicioMouseExited(evt);
            }
        });
        btnRegresarVentanaInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarVentanaInicioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNombreCliente)
                    .addComponent(lblGeneroCliente)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(lblIdCliente)
                                    .addGap(75, 75, 75))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(lblApellidoCliente)
                                    .addGap(42, 42, 42))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblEdadCliente)
                                    .addGap(60, 60, 60)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblContactoCliente)
                                .addGap(37, 37, 37)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtIdCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                            .addComponent(txtNombreCliente)
                            .addComponent(txtGeneroCliente)
                            .addComponent(txtEdadCliente)
                            .addComponent(txtContactoCliente)
                            .addComponent(txtApellidoCliente)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnEliminarTdoCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnModificarCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEliminarCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAgregarCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblFilaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblColumnaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblNuevoDatoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(117, 117, 117)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtFilaCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                                .addComponent(txtColumnaCliente)
                                .addComponent(txtNuevoDatoCliente))))
                    .addComponent(btnRegresarVentanaInicio, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblIdCliente)
                            .addComponent(txtIdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNombreCliente)
                            .addComponent(txtNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblApellidoCliente)
                            .addComponent(txtApellidoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblGeneroCliente)
                            .addComponent(txtGeneroCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEdadCliente)
                            .addComponent(txtEdadCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblContactoCliente)
                            .addComponent(txtContactoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnAgregarCliente)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblFilaCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                            .addComponent(txtFilaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnEliminarCliente)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblColumnaCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                            .addComponent(txtColumnaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEliminarTdoCliente)
                    .addComponent(lblNuevoDatoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNuevoDatoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnModificarCliente)
                    .addComponent(btnRegresarVentanaInicio))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarClienteActionPerformed
        // TODO add your handling code here:
        String [] dates = new String [6];
        dates [0] = txtIdCliente.getText();
        dates [1] = txtNombreCliente.getText();
        dates [2] = txtApellidoCliente.getText();
        dates [3] = txtGeneroCliente.getText();
        dates [4] = txtEdadCliente.getText();
        dates [5] = txtContactoCliente.getText();
        modelo.addRow(dates);
        txtIdCliente.setText("");
        txtNombreCliente.setText("");
        txtApellidoCliente.setText("");
        txtGeneroCliente.setText("");
        txtEdadCliente.setText("");
        txtContactoCliente.setText("");
    }//GEN-LAST:event_btnAgregarClienteActionPerformed

    private void btnEliminarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarClienteActionPerformed
        // TODO add your handling code here:
        int fila = tablaCliente.getSelectedRow();
        if (fila >= 0 ){
            modelo.removeRow(fila);
        }else{
            JOptionPane.showMessageDialog(null,"Seleccionar Fila");
        }
    }//GEN-LAST:event_btnEliminarClienteActionPerformed

    private void btnEliminarTdoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarTdoClienteActionPerformed
        // TODO add your handling code here:
        int fila = tablaCliente.getRowCount();
        for (int i = fila -1;i>=0;i--){
            modelo.removeRow(i);
        }
    }//GEN-LAST:event_btnEliminarTdoClienteActionPerformed

    private void btnModificarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarClienteActionPerformed
        // TODO add your handling code here:
        int fila = Integer.parseInt(txtFilaCliente.getText());
        int columna = Integer.parseInt(txtColumnaCliente.getText());
        modelo.setValueAt(txtNuevoDatoCliente.getText(),fila,columna);
        //PARA QUE FUNCIONE, SE CUENTA DESDE 0 
        //COLUMNA ID = 0, NOMBRE = 1, Y ASI SUCESIVAMENTE
    }//GEN-LAST:event_btnModificarClienteActionPerformed

    private void btnRegresarVentanaInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarVentanaInicioActionPerformed
        // TODO add your handling code here:
        VentanaInicio wer = new VentanaInicio();
        wer.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_btnRegresarVentanaInicioActionPerformed

    private void btnRegresarVentanaInicioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegresarVentanaInicioMouseEntered
        // TODO add your handling code here:
        btnRegresarVentanaInicio.setBackground(Color.cyan);
        btnRegresarVentanaInicio.setForeground(Color.black);
    }//GEN-LAST:event_btnRegresarVentanaInicioMouseEntered

    private void btnRegresarVentanaInicioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegresarVentanaInicioMouseExited
        // TODO add your handling code here:
        btnRegresarVentanaInicio.setBackground(Color.black);
        btnRegresarVentanaInicio.setForeground(Color.white);
    }//GEN-LAST:event_btnRegresarVentanaInicioMouseExited

    private void txtFilaClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtFilaClienteMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFilaClienteMouseClicked

    private void txtFilaClienteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtFilaClienteMousePressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtFilaClienteMousePressed

    private void txtFilaClienteMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtFilaClienteMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFilaClienteMouseReleased

    private void txtFilaClienteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtFilaClienteMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFilaClienteMouseExited

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarCliente;
    private javax.swing.JButton btnEliminarCliente;
    private javax.swing.JButton btnEliminarTdoCliente;
    private javax.swing.JButton btnModificarCliente;
    private javax.swing.JButton btnRegresarVentanaInicio;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblApellidoCliente;
    private javax.swing.JLabel lblColumnaCliente;
    private javax.swing.JLabel lblContactoCliente;
    private javax.swing.JLabel lblEdadCliente;
    private javax.swing.JLabel lblFilaCliente;
    private javax.swing.JLabel lblGeneroCliente;
    private javax.swing.JLabel lblIdCliente;
    private javax.swing.JLabel lblNombreCliente;
    private javax.swing.JLabel lblNuevoDatoCliente;
    private javax.swing.JTable tablaCliente;
    private javax.swing.JTextField txtApellidoCliente;
    private javax.swing.JTextField txtColumnaCliente;
    private javax.swing.JTextField txtContactoCliente;
    private javax.swing.JTextField txtEdadCliente;
    private javax.swing.JTextField txtFilaCliente;
    private javax.swing.JTextField txtGeneroCliente;
    private javax.swing.JTextField txtIdCliente;
    private javax.swing.JTextField txtNombreCliente;
    private javax.swing.JTextField txtNuevoDatoCliente;
    // End of variables declaration//GEN-END:variables
}
