/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.cristiangarcia.login;
/**
 *
 * @author crist
 */
import java.awt.Color;
import org.cristiangarcia.principal.VentanaInicio;
public class Login extends javax.swing.JFrame {
    int xMouse,yMouse;
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitleLogin = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblContraseñaLogin = new javax.swing.JLabel();
        txtUsuarioLogin = new javax.swing.JTextField();
        lblUsuarioLogin = new javax.swing.JLabel();
        jPasswordLogin = new javax.swing.JPasswordField();
        btnExit = new javax.swing.JButton();
        panelMovimiento = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        btnIngresarLogin = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel4 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(800, 400));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitleLogin.setBackground(new java.awt.Color(0, 255, 204));
        lblTitleLogin.setFont(new java.awt.Font("Lemon Days", 0, 36)); // NOI18N
        lblTitleLogin.setForeground(new java.awt.Color(255, 255, 255));
        lblTitleLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitleLogin.setText("AGENCIA DE VIAJES");
        getContentPane().add(lblTitleLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(447, 79, 354, -1));

        jPanel1.setBackground(new java.awt.Color(53, 87, 100));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 850, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 850, 130));

        lblContraseñaLogin.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        lblContraseñaLogin.setText("CONTRASEÑA");
        getContentPane().add(lblContraseñaLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 261, -1, 33));

        txtUsuarioLogin.setForeground(new java.awt.Color(204, 204, 204));
        txtUsuarioLogin.setText("Juan Perez");
        txtUsuarioLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtUsuarioLoginMousePressed(evt);
            }
        });
        getContentPane().add(txtUsuarioLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 221, 250, -1));

        lblUsuarioLogin.setBackground(new java.awt.Color(0, 0, 0));
        lblUsuarioLogin.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        lblUsuarioLogin.setText("USUARIO");
        getContentPane().add(lblUsuarioLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 173, 91, 33));

        jPasswordLogin.setForeground(new java.awt.Color(204, 204, 204));
        jPasswordLogin.setText("**********");
        jPasswordLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPasswordLoginMousePressed(evt);
            }
        });
        getContentPane().add(jPasswordLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 311, 250, -1));

        btnExit.setText("X");
        btnExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnExitMouseExited(evt);
            }
        });
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        getContentPane().add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 38, 33));

        panelMovimiento.setBackground(new java.awt.Color(255, 255, 255));
        panelMovimiento.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                panelMovimientoMouseDragged(evt);
            }
        });
        panelMovimiento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelMovimientoMousePressed(evt);
            }
        });

        javax.swing.GroupLayout panelMovimientoLayout = new javax.swing.GroupLayout(panelMovimiento);
        panelMovimiento.setLayout(panelMovimientoLayout);
        panelMovimientoLayout.setHorizontalGroup(
            panelMovimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 850, Short.MAX_VALUE)
        );
        panelMovimientoLayout.setVerticalGroup(
            panelMovimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        getContentPane().add(panelMovimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 0, 850, 33));

        jPanel2.setBackground(new java.awt.Color(90, 143, 123));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 560, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 560, 240));

        jPanel3.setBackground(new java.awt.Color(53, 87, 100));

        btnIngresarLogin.setBackground(new java.awt.Color(118, 186, 153));
        btnIngresarLogin.setFont(new java.awt.Font("Lemon Days", 0, 36)); // NOI18N
        btnIngresarLogin.setText("INGRESAR");
        btnIngresarLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnIngresarLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnIngresarLoginMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnIngresarLoginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnIngresarLoginMouseExited(evt);
            }
        });
        btnIngresarLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarLoginActionPerformed(evt);
            }
        });

        jSeparator1.setForeground(new java.awt.Color(51, 255, 204));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addComponent(btnIngresarLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73)
                .addComponent(btnIngresarLogin)
                .addContainerGap(102, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 160, 290, 240));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 850, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIngresarLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIngresarLoginMouseClicked
        // TODO add your handling code here:
        VentanaInicio trg = new VentanaInicio();
        if (txtUsuarioLogin.getText().equals("Cristian Garcia")){
             if (String.valueOf(jPasswordLogin.getPassword()).equals("ADMIN")){
                 trg.setVisible(true);
                 this.setVisible(false);
             }else{
                 javax.swing.JOptionPane.showMessageDialog(this,"Datos incorrectos");
             }
            
        }else{
            javax.swing.JOptionPane.showMessageDialog(this,"Datos incorrectos");
        }
        
    }//GEN-LAST:event_btnIngresarLoginMouseClicked

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnExitMouseClicked

    private void panelMovimientoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelMovimientoMousePressed
        // TODO add your handling code here:
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_panelMovimientoMousePressed

    private void panelMovimientoMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelMovimientoMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse,y - yMouse);
    }//GEN-LAST:event_panelMovimientoMouseDragged

    private void btnExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseEntered
        // TODO add your handling code here:
        btnExit.setBackground(Color.red);
        btnExit.setForeground(Color.white);
    }//GEN-LAST:event_btnExitMouseEntered

    private void btnExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseExited
        // TODO add your handling code here:
        btnExit.setBackground(Color.white);
        btnExit.setForeground(Color.black);
    }//GEN-LAST:event_btnExitMouseExited

    private void txtUsuarioLoginMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUsuarioLoginMousePressed
        // TODO add your handling code here:
        if (txtUsuarioLogin.getText().equals("Juan Perez")){
            txtUsuarioLogin.setText("");
            txtUsuarioLogin.setForeground(Color.black);
        }
        if (String.valueOf(jPasswordLogin.getPassword()).isEmpty()){
            jPasswordLogin.setText("**********");   
            jPasswordLogin.setForeground(Color.gray);
        }  
    }//GEN-LAST:event_txtUsuarioLoginMousePressed

    private void jPasswordLoginMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPasswordLoginMousePressed
        // TODO add your handling code here:
        if (String.valueOf(jPasswordLogin.getPassword()).equals("**********")){
            jPasswordLogin.setText(""); 
            jPasswordLogin.setForeground(Color.black);
        }
        if (txtUsuarioLogin.getText().isEmpty()){
            txtUsuarioLogin.setText("Juan Perez");  
            txtUsuarioLogin.setForeground(Color.gray); 
        }    
    }//GEN-LAST:event_jPasswordLoginMousePressed

    private void btnIngresarLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnIngresarLoginActionPerformed

    private void btnIngresarLoginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIngresarLoginMouseEntered
        // TODO add your handling code here:
        btnIngresarLogin.setBackground(Color.black);
        btnIngresarLogin.setForeground(new Color(118, 186, 153));
    }//GEN-LAST:event_btnIngresarLoginMouseEntered

    private void btnIngresarLoginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIngresarLoginMouseExited
        // TODO add your handling code here:
        btnIngresarLogin.setBackground(new Color(118, 186, 153));
        btnIngresarLogin.setForeground(Color.black);
    }//GEN-LAST:event_btnIngresarLoginMouseExited

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnIngresarLogin;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPasswordField jPasswordLogin;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblContraseñaLogin;
    private javax.swing.JLabel lblTitleLogin;
    private javax.swing.JLabel lblUsuarioLogin;
    private javax.swing.JPanel panelMovimiento;
    private javax.swing.JTextField txtUsuarioLogin;
    // End of variables declaration//GEN-END:variables
}
